version: '3.1'
services:
  moodle:
    container_name: moodle-app
    image: moodle_all_in_one:dev
    restart: always
    environment:
      TZ: Europe/Berlin
      MOODLE_HOST: localhost
      MOODLE_PORT: 9090
    ports:
      - 9090:9090
    volumes:
      - ~:/var/lib/mysql/